### PR TITLE
Bump the minitest-metadata dependency

### PR DESCRIPTION
**Pull request by fbernier**

### CODE REVIEW

**Comment by blowmage** [comment]
Why?

**Comment by fbernier** [comment]
The latest release contains performance improvements and have been released for over a year. I guess it doesn't hurt to bump it. I just noticed it when running `bundle outdated` returned only this gem on one of my rails app.

No worries if you think it's completely unnecessary.

**Comment by blowmage** [comment]
Makes sense. Thanks for the explanation.

**Comment by mateuszgorniak** [comment]
Could you bump dependency version? ;-)

**Comment by knightq** [comment]
Merge, please

**Comment by blowmage** [comment]
The change here is to the gemspec file, but unfortunately it needs to be applied to the Rakefile, which generates the gemspec.

I've updated the dependencies and released 2.1.2.

**Pull request closed without merging**
