### PR TITLE
Updated dependencies and removed support for 1.9.3

### PR DESCRIPTION
**Pull request by rhymes**

### CODE REVIEW

**Comment by blowmage** [comment]
Rubies and dependencies are updated in master to support Rails 5. Thanks.

**Comment by rhymes** [comment]
@blowmage I understand, though with the latest updates of minitest-rails and minitest-rails-capybara you completely dropped support for Rails 4.2 :-(

**Comment by blowmage** [comment]
Rails 4.1 and 4.2 are supported by minitest-rails versions 2.x found on the 2.x branch. The 2.x branch also had the dependencies updated and 2.1.2 was released yesterday. It still supports Ruby 1.9.3 though.

**Comment by rhymes** [comment]
@blowmage thanks! sorry I didn't see the new release. Perfect!

**Pull request closed without merging**
